#!/usr/bin/env python3
"""Generate a TFT_eSPI smooth (VLW) font containing only the glyphs we need for
numbers, and emit it as a PROGMEM C array.

VLW format (all big-endian int32):
  header: glyphCount, version(11), fontSize, 0, ascent, descent
  per glyph (sorted by codepoint): codepoint, height, width, xAdvance, dY, dX, 0
  then: concatenated 8-bit alpha bitmaps (width*height, row-major) in glyph order

Usage: python3 tools/gen_smooth_font.py > include/smooth_font.h
"""
import struct, sys
from PIL import Image, ImageFont, ImageDraw

FONT = "/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf"   # OFL-1.1: Noto Sans
SIZE = 24
CHARS = "0123456789,.%:-"

font = ImageFont.truetype(FONT, SIZE)
ascent, descent = font.getmetrics()

glyphs = []
for ch in CHARS:
    l, t, r, b = font.getbbox(ch)
    w, h = r - l, b - t
    if w <= 0 or h <= 0:
        w, h, alpha = 1, 1, bytes([0])
    else:
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((-l, -t), ch, fill=255, font=font)
        alpha = img.tobytes()  # row-major w*h, 8-bit coverage
    adv = round(font.getlength(ch))
    glyphs.append((ord(ch), h, w, adv, ascent - t, l, alpha))

glyphs.sort(key=lambda g: g[0])

buf = bytearray()
def wi(v): buf.extend(struct.pack(">i", v))
wi(len(glyphs)); wi(11); wi(SIZE); wi(0); wi(ascent); wi(descent)
for cp, h, w, adv, dY, dX, _ in glyphs:
    wi(cp); wi(h); wi(w); wi(adv); wi(dY); wi(dX); wi(0)
for g in glyphs:
    buf.extend(g[6])

print(f"// VLW smooth font: '{CHARS}' size {SIZE}, {len(buf)} bytes", file=sys.stderr)
print("// Auto-generated by tools/gen_smooth_font.py -- do not edit by hand.")
print("#pragma once")
print("#include <stdint.h>")
print("#include <pgmspace.h>")
print(f"static const uint8_t PRICE_FONT[] PROGMEM = {{ {','.join(str(b) for b in buf)} }};")
