#!/usr/bin/env python3
"""Download coin logos from CoinGecko, convert to small RGB565 bitmaps, emit a C header.

Coins are fixed, so logos are baked into the firmware (no runtime download).
Usage: python3 tools/gen_coin_logos.py > include/coin_logos.h
"""
import io, sys, urllib.request
from PIL import Image

SIZE = 22  # icon size in px (square)
UA = "Glance/1.0 (build tool)"

# (C identifier, CoinGecko coin id)
COINS = [("LOGO_BTC", "bitcoin"), ("LOGO_ETH", "ethereum"), ("LOGO_KAIA", "kaia")]


def fetch_json(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    import json
    return json.load(urllib.request.urlopen(req, timeout=20))


def fetch_bytes(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    return urllib.request.urlopen(req, timeout=20).read()


def to_rgb565(cid):
    meta = fetch_json(
        f"https://api.coingecko.com/api/v3/coins/{cid}"
        "?localization=false&tickers=false&market_data=false"
        "&community_data=false&developer_data=false&sparkline=false"
    )
    url = meta["image"].get("large") or meta["image"].get("small")
    img = Image.open(io.BytesIO(fetch_bytes(url))).convert("RGBA")
    img = img.resize((SIZE, SIZE), Image.LANCZOS)
    bg = Image.new("RGB", (SIZE, SIZE), (0, 0, 0))  # composite over black (screen bg)
    bg.paste(img, (0, 0), img)
    words = []
    for y in range(SIZE):
        for x in range(SIZE):
            r, g, b = bg.getpixel((x, y))
            words.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))
    return words


print("// Auto-generated by tools/gen_coin_logos.py -- do not edit by hand.")
print("#pragma once")
print("#include <stdint.h>")
print("#include <pgmspace.h>")
print()
print("struct CoinLogo { const uint16_t* data; uint8_t w; uint8_t h; };")
print()
for ident, cid in COINS:
    words = to_rgb565(cid)
    arr = ident.lower() + "_data"
    body = ", ".join("0x%04X" % w for w in words)
    print(f"// {cid}  {SIZE}x{SIZE}", file=sys.stderr)
    print(f"static const uint16_t {arr}[] PROGMEM = {{ {body} }};")
    print(f"static const CoinLogo {ident} = {{ {arr}, {SIZE}, {SIZE} }};")
    print()
