#!/usr/bin/env python3
"""Render a fixed set of Korean/mixed labels to 1-bit bitmaps and emit a C header.

Only the exact label strings used by the firmware are baked in, so the flash cost
is tiny (a few hundred bytes each) instead of a full CJK font.

Usage: python3 tools/gen_kr_labels.py > include/kr_labels.h
"""
from PIL import Image, ImageDraw, ImageFont

FONT_KR  = "/usr/share/fonts/opentype/noto/NotoSansCJK-Medium.ttc"   # Korean labels
FONT_SYM = "/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf"               # OFL-1.1: Noto Sans
FONT_KR_INDEX = 1  # Noto Sans CJK KR face in the TTC
THRESHOLD = 128         # luminance cutoff for on/off pixel

# (C identifier, display string, glyph height in px, font)
LABELS = [
    ("KR_KOSPI",       "코스피",      20, FONT_KR),
    ("KR_SS",          "삼성전자",    20, FONT_KR),
    ("KR_HYNIX",       "SK하이닉스",  20, FONT_KR),
    ("KR_USDKRW",      "달러/원",     20, FONT_KR),
    ("KR_INV",         "인버스",      20, FONT_KR),
    ("KR_INV2",        "인버스X2",    20, FONT_KR),
    ("KR_LEV",         "레버리지",    20, FONT_KR),
    ("KR_TITLE_STOCK",  "주식시장",   24, FONT_KR),  # stock page header
    ("KR_TITLE_CRYPTO", "코인시장",   24, FONT_KR),  # crypto page header
    ("KR_TITLE_DOLLAR", "달러시장",   24, FONT_KR),  # dollar/fx page header
]  # coin logos are real bitmaps -> see tools/gen_coin_logos.py

_font_cache = {}
def get_font(size, path):
    key = (size, path)
    if key not in _font_cache:
        _font_cache[key] = ImageFont.truetype(path, size, index=FONT_KR_INDEX if path == FONT_KR else 0)
    return _font_cache[key]


def render(text, size, path):
    font = get_font(size, path)
    # measure
    tmp = Image.new("L", (4, 4), 0)
    d = ImageDraw.Draw(tmp)
    x0, y0, x1, y1 = d.textbbox((0, 0), text, font=font)
    w, h = x1 - x0, y1 - y0
    img = Image.new("L", (w, h), 0)
    d = ImageDraw.Draw(img)
    d.text((-x0, -y0), text, fill=255, font=font)

    byte_w = (w + 7) // 8
    data = bytearray()
    for row in range(h):
        for bw in range(byte_w):
            b = 0
            for bit in range(8):
                x = bw * 8 + bit
                if x < w and img.getpixel((x, row)) >= THRESHOLD:
                    b |= (0x80 >> bit)
            data.append(b)
    return w, h, bytes(data)


print("// Auto-generated by tools/gen_kr_labels.py -- do not edit by hand.")
print("#pragma once")
print("#include <stdint.h>")
print("#include <pgmspace.h>")
print()
print("struct KRLabel { const uint8_t* data; uint16_t w; uint16_t h; };")
print()

for ident, text, size, path in LABELS:
    w, h, data = render(text, size, path)
    arr = ident.lower() + "_data"
    hexbytes = ", ".join("0x%02X" % b for b in data)
    print(f"// \"{text}\"  {w}x{h}, {len(data)} bytes")
    print(f"static const uint8_t {arr}[] PROGMEM = {{ {hexbytes} }};")
    print(f"static const KRLabel {ident} = {{ {arr}, {w}, {h} }};")
    print()
