#!/usr/bin/env python3
"""Generate anti-aliased RGB565 splash marks for the Glance boot screen.

Usage:
    python3 tools/gen_splash_marks.py > include/splash_marks.h
"""

from PIL import Image, ImageDraw


SCALE = 4
WIDTH = 120
HEIGHT = 58
BG = (0, 0, 0)
CHART = (255, 77, 61)
VARIANTS = (("SPLASH_MARK_ORANGE", (215, 112, 18)),)


def scaled(points):
    return [(x * SCALE, y * SCALE) for x, y in points]


def render(frame_color):
    img = Image.new("RGB", (WIDTH * SCALE, HEIGHT * SCALE), BG)
    draw = ImageDraw.Draw(img)
    draw.rounded_rectangle(
        (2 * SCALE, 2 * SCALE, 117 * SCALE, 55 * SCALE),
        radius=8 * SCALE,
        outline=frame_color,
        width=2 * SCALE,
    )

    # Preserve the six-point rising trace from the original Ultra splash.
    chart = scaled(((13, 43), (31, 34), (50, 38), (68, 22), (86, 28), (103, 9)))
    draw.line(chart, fill=CHART, width=3 * SCALE, joint="curve")

    # The Ultra used a distinctive right-angle arrowhead.
    tip = (103 * SCALE, 9 * SCALE)
    draw.line((tip, (95 * SCALE, 9 * SCALE)), fill=CHART, width=3 * SCALE)
    draw.line((tip, (103 * SCALE, 18 * SCALE)), fill=CHART, width=3 * SCALE)
    return img.resize((WIDTH, HEIGHT), Image.Resampling.LANCZOS)


def rgb565(pixel):
    r, g, b = pixel
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


print("// Auto-generated by tools/gen_splash_marks.py -- do not edit by hand.")
print("#pragma once")
print("#include <stdint.h>")
print("#include <pgmspace.h>")
print('#include "coin_logos.h"')

for ident, frame in VARIANTS:
    image = render(frame)
    words = [rgb565(pixel) for pixel in image.getdata()]
    array_name = ident.lower() + "_data"
    values = ",".join(f"0x{word:04X}" for word in words)
    print(f"static const uint16_t {array_name}[] PROGMEM = {{ {values} }};")
    print(f"static const CoinLogo {ident} = {{ {array_name}, {WIDTH}, {HEIGHT} }};")
