#!/usr/bin/env python3
"""Generate a large TFT_eSPI smooth (VLW) font for the night clock (digits + colon).
Usage: python3 tools/gen_clock_font.py > include/smooth_clock.h
See gen_smooth_font.py for the VLW format notes.
"""
import struct, sys
from PIL import Image, ImageFont, ImageDraw

FONT = "/usr/share/fonts/truetype/noto/NotoSansDisplay-Regular.ttf"
SIZE = 72
CHARS = "0123456789:"
NAME = "CLOCK_FONT"

font = ImageFont.truetype(FONT, SIZE)
ascent, descent = font.getmetrics()

glyphs = []
for ch in CHARS:
    l, t, r, b = font.getbbox(ch)
    w, h = r - l, b - t
    if w <= 0 or h <= 0:
        w, h, alpha = 1, 1, bytes([0])
    else:
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((-l, -t), ch, fill=255, font=font)
        alpha = img.tobytes()
    glyphs.append((ord(ch), h, w, round(font.getlength(ch)), ascent - t, l, alpha))

glyphs.sort(key=lambda g: g[0])
buf = bytearray()
def wi(v): buf.extend(struct.pack(">i", v))
wi(len(glyphs)); wi(11); wi(SIZE); wi(0); wi(ascent); wi(descent)
for cp, h, w, adv, dY, dX, _ in glyphs:
    wi(cp); wi(h); wi(w); wi(adv); wi(dY); wi(dX); wi(0)
for g in glyphs:
    buf.extend(g[6])

print(f"// VLW clock font: '{CHARS}' size {SIZE}, {len(buf)} bytes", file=sys.stderr)
print("// Auto-generated by tools/gen_clock_font.py -- do not edit by hand.")
print("#pragma once")
print("#include <stdint.h>")
print("#include <pgmspace.h>")
print(f"static const uint8_t {NAME}[] PROGMEM = {{ {','.join(str(b) for b in buf)} }};")
