#!/usr/bin/env python3
"""Render the splash title ("Glance") in Noto Sans Display, anti-aliased, to an RGB565 bitmap.
Reuses the CoinLogo struct (see coin_logos.h) so it blits with drawLogo().
Usage: python3 tools/gen_title.py > include/title_logo.h
"""
import sys
from PIL import Image, ImageFont, ImageDraw

FONT = "/usr/share/fonts/truetype/noto/NotoSansDisplay-Bold.ttf"
IDX  = 0          # OFL-1.1: Noto Sans Display Bold
TEXT = "Glance"
SIZE = 46
LS   = 3          # letter spacing (px)
IDENT = "TITLE_GLANCE"

font = ImageFont.truetype(FONT, SIZE, index=IDX)
asc, desc = font.getmetrics()

# lay out each glyph with extra letter spacing
adv = [font.getlength(c) for c in TEXT]
total = int(sum(adv) + LS * (len(TEXT) - 1)) + 6
img = Image.new("L", (total, asc + desc), 0)
d = ImageDraw.Draw(img)
x = 0.0
for c, a in zip(TEXT, adv):
    d.text((x, 0), c, fill=255, font=font)
    x += a + LS

img = img.crop(img.getbbox())          # trim to ink
W, H = img.size

words = []
for y in range(H):
    for xx in range(W):
        a = img.getpixel((xx, y))       # AA intensity 0..255 (white text on black)
        words.append(((a & 0xF8) << 8) | ((a & 0xFC) << 3) | (a >> 3))

print(f"// {TEXT} in Noto Sans Display Bold, {W}x{H}", file=sys.stderr)
print("// Auto-generated by tools/gen_title.py -- do not edit by hand.")
print('#pragma once')
print('#include <stdint.h>')
print('#include <pgmspace.h>')
print('#include "coin_logos.h"   // for the CoinLogo struct + drawLogo')
arr = IDENT.lower() + "_data"
print(f"static const uint16_t {arr}[] PROGMEM = {{ {','.join('0x%04X' % w for w in words)} }};")
print(f"static const CoinLogo {IDENT} = {{ {arr}, {W}, {H} }};")
